[general]
log_dir = "lightning_logs"
hparams_file = "hparams.yaml"
cache_enabled = true

[ignored_parameters]
parameters = [
    "fold",
    "devices",
    "random_seed",
    "timestamp",
    "worker_id",
    "run_id",
    "version",
    "trainer-precision",
    "trainer-max_epochs",
    "trainer-devices",
    "trainer-num_sanity_val_steps",
    "trainer-check_val_every_n_epoch",
    "trainer-enable_progress_bar",
    "trainer-accelerator",
    "trainer-enable_model_summary",
    "trainer-log_every_n_steps",
    "trainer-benchmark",
    "num_workers",
]

[tolerance]
float_tolerance = 0.001
int_tolerance = 0
string_case_sensitive = false

[grouping]
main_key = ["model_name", "dataset"]
group_by_all_parameters = true
# grouping_parameters = [
#     "model_type",
#     "dataset",
#     "learning_rate",
# ]
similarity_threshold = 1

[diff]
show_detailed_diff = true
diff_format = "key: value1 vs value2"
highlight_diff_keys = true

[tui]
color_theme = "default"
colors = { same_experiment = "green", similar_experiment = "yellow", selected = "blue", background = "black", text = "white", border = "cyan", highlight = "white", status_bar_bg = "dark_gray", status_bar_text = "white" }
layout = "list"
show_help_bar = true
auto_expand_groups = false
detail_panel_position = "Bottom"
refresh_rate_ms = 250
version_panel_proportion = 70
status_bar_height = 3
scroll_indicators = true

[keybindings]
up = "up"
down = "down"
left = "left"
right = "right"
select = "space"
confirm = "enter"
quit = "q"
help = "h"
filter = "/"
switch_view = "v"
scroll_detail_up = "u"
scroll_detail_down = "d"

[test_script]
path = "test.py"
default_args = { filter = "", sort_key = "fold" }
prompt_for_args = true
fixed_args = []
